spring:
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:sqlserver://10.6.100.103;DatabaseName=temp
    username: test
    password: test123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
mybatis:
  configuration:
    cache-enabled: true
  mapper-locations: mapper/*.xml